### ISSUE TITLE
On android, choosing Google Maps fallbacks on native app selection 

### ISSUE THREAD

**Issue by AmauryLiet** [flexible-agency/react-native-map-link#138]
Hey there!

Just came across an issue on android, 
All works well for every app I select except Google Maps (the major one unfortunately): when I select it, instead of seeing the app opening, I see the native app selector

![Screenshot_20200605-235218_Android System](https://user-images.githubusercontent.com/9596435/83926613-a42d9e80-a78a-11ea-992d-b3676925ccbd.jpg)

Thanks again for the hard work ;)

**Comment by tschoffelen** [comment]
That's very annoying! The reason for that is that a lot of apps now act like they are Google Maps (ie listen to the Google Maps URI scheme), and I'm not aware yet of a way to directly open Google Maps without that app chooser showing up if there's more than one app that matches the URI scheme.

**Comment by AmauryLiet** [comment]
Indeed the `maps.google.com` links appears to be handled by all of these 'parasite' apps

The way around might be to work with Google recommended way of working with [Intent](https://developers.google.com/maps/documentation/urls/android-intents) for android

Not sure how it would fit with the current implementation though (you might need a native part)

**Comment by tschoffelen** [comment]
This might have been solved by #158.

**Comment by komolova** [comment]
This issue could be fixed by using google maps cross-platform universal URLs instead of 'geo:' intent for Android. The google maps [docs](https://developers.google.com/maps/documentation/urls/android-intents#intent_requests) said "In order to launch Google Maps with an intent you must first create an Intent object, specifying its action, URI and package." I guess there is missing some native part for android.

**Comment by tschoffelen** [comment]
Hi @komolova!

Indeed, it would be possible to do using intents. My reason for initially not doing that was that it would complicate the installation of the package, but now that RN supports auto-linking for Android too, there is not really a reason to not add this, except for the fact that 1) I haven't had time to look into this yet, 2) My Java knowledge is very very limited 😄 

**So if anyone would be able to open a PR for this, that would be super helpful.**

Maybe this other package might serve as a bit of an inspiration, as it also uses intents on Android: https://github.com/flexible-agency/react-native-email-link

**Comment by tschoffelen** [comment]
That's actually what we do at the moment, but multiple apps tell Android that they are able to open 'maps.google.com' links, like Uber and CityMapper.

**Comment by komolova** [comment]
@tschoffelen 
As I see in a [source code](https://github.com/flexible-agency/react-native-map-link/blob/5eb530fa5b3440f4f3a83f8bf64d44d5fb6b7c0c/src/constants.js#L35) of this library 
For android the 'geo:' scheme is using, not 'maps.google.com' .
I think using geo scheme without specifying a package let the Android system ask user to choose an app.  To specify a package that you want to handle this scheme, you need to create an Intent and set google maps package.

That’s why I’m talking about using cross-platform URls scheme instead of 'geo:'.  This type of url looks like “https://www.google.com/maps/search/?api=1&parameters” for search a place. 
If google maps is available on the device, the url launches google maps app, if not it launches google maps in a browser. 
https://developers.google.com/maps/documentation/urls/get-started#forming-the-search-url.

**Comment by tschoffelen** [comment]
Hi @komolova, we were using `maps.google.com` for a while, and then switched to `geo:` in the previous version of the library, but recently switched back to `maps.google.com` because it was creating all sorts of issues.

But apps like Uber and CityMapper listen to both of these unfortunately.

Current version: https://github.com/flexible-agency/react-native-map-link/blob/master/src/constants.js#L35

**Comment by komolova** [comment]
Ok, so why are you using 'maps.google.com'? Maps URLs doc says it should be 'www.google.com/maps/...'.
For example "https://www.google.com/maps/dir/?api=1&parameters" or “https://www.google.com/maps/search/?api=1&parameters”

**Comment by tschoffelen** [comment]
Ah good point, I wasn't reading well. I don't know if that makes a difference though? But happy to try it.

**Comment by tschoffelen** [comment]
Amazing! Would you mind opening a PR?

**Comment by tschoffelen** [comment]
Thanks @komolova!
