### ISSUE TITLE
Google Maps ignores query_place_id parameter

### ISSUE THREAD

**Issue by kennethwyu** [flexible-agency/react-native-map-link#155]
Version `2.7.18` passes `query_place_id` to `maps.google.com` in the following format:
https://maps.google.com/?q=38.897683,-77.036531&query_place_id=ChIJ37HL3ry3t4kRv3YLbdhpWXE

While this URL does pull up the correct latitude and longitude, it doesn't appear to actually pull up the appropriate Google Maps Place information.

Per Google Maps' [Universal Cross-Platform Syntax](https://developers.google.com/maps/documentation/urls/get-started), the URL can be formed as:
https://www.google.com/maps/search/?api=1&query=38.897683,-77.036531&query_place_id=ChIJ37HL3ry3t4kRv3YLbdhpWXE

This brings up the proper place information and uses latitude / longitude as a fallback. Note the prefix of **www.google.com/maps/search/?api=1&query=**. 

I'm not sure if this works on the `comgooglemaps://` scheme either, as the documentation makes no mention of support for `query_place_id`.

Given Google's recommendation of using Universal Links on iOS 9 and above, it may make sense to move away from the URL scheme and adjust the query accordingly.

**Comment by tschoffelen** [comment]
We should probably indeed make [this line](https://github.com/flexible-agency/react-native-map-link/blob/master/src/index.js#L94) just use the HTTP URL.

We can't do that for the detection mechanism (the `prefixes` object), because there's no way on iOS to determine if an app is installed using a Universal Link, and we don't want to show Google Maps if the user doesn't have the app installed (unless option `alwaysIncludeGoogle` is true of course).

Feel free to submit a PR. Thanks!

**Comment by kennethwyu** [comment]
Thanks for the reply; I've worked around this thus far by updating the HTTP url in `constants`, setting `alwaysIncludeGoogle ` to true and and building the query accordingly (either `?api=1&query=` or `?q=`, based on whether we're using Universal Link or URL scheme). 

Can definitely submit a PR but wanted to get your thoughts (`query_place_id` might not be the only parameter that doesn't work in the current implementation) as we might need to update the readme accordingly to indicate the limitations with using URL scheme.

**Comment by tschoffelen** [comment]
Fixed in version `2.7.22`.
