### ISSUE TITLE
appsWhiteList not working on android

### ISSUE THREAD

**Issue by nikoloz110** [flexible-agency/react-native-map-link#171]
I have it set like this
```
showLocation({
      latitude: Number(latLng[0]),
      longitude: Number(latLng[1]),
      alwaysIncludeGoogle: true,
      appsWhiteList: ["google-maps", "apple-maps"],
    });
```
but I am still seeing 'Bolt' & 'Yandex" suggestions
![161796626_202205154990364_1782361589637028958_n](https://user-images.githubusercontent.com/17814568/111611626-19d49980-87f6-11eb-8b6f-f926563252a6.png)
 while opening the map
android 10

**Comment by tschoffelen** [comment]
Hey, this is actually related to #138.

The library correctly detects that only one option is available based on the whitelist you've set ('google-maps'), so it immediately opens that app. Unfortunately, Bolt and Yandex Go both 'hijack' Google Maps by telling Android that they're able to open maps.google.com, which is why the system native app chooser is then shown.

There's unfortunately not too much we can do about that, except for switching to Android Intents.
