### ISSUE TITLE
Always Show Popup only installed one map app 

### ISSUE THREAD

**Issue by OnurSevket** [flexible-agency/react-native-map-link#193]
Hi,

I am using the popup component, but although there is only one map application on my phone, it is constantly waiting for me to choose a map application. If only One application is installed, is it possible to open a loaded map automatically?

![image](https://user-images.githubusercontent.com/23638184/130442915-4b07d649-6d3c-457b-a402-c346bd5c2ee6.png)

**Comment by tschoffelen** [comment]
Hi there!

I think that's not supported with the popup since it was causing problems with the modal being immediately dismissed once it's brought up.

The default mode of using the library does support it.

Alternatively, you can probably work around it by first calling [the `getAvailableApps` function](https://github.com/flexible-agency/react-native-map-link/blob/master/src/utils.js#L12) directly.

**Comment by OnurSevket** [comment]
Thanks for answer,

If possible, can you explain how I can access internal functions?

**Comment by tschoffelen** [comment]
You should be able to do something like:

```js
import { getAvailableApps } from "react-native-map-link/src/utils";
```
