### ISSUE TITLE
Not showing action sheet or alert on showLocation.

### ISSUE THREAD

**Issue by qaws5503** [flexible-agency/react-native-map-link#209]
Hi, I'm facing the problem I mentioned in the title. When I use `showLocation` it immediately jump to the default map without asking which app I want to use. Which isn't the correct behavior mentioned in [README.md](https://github.com/flexible-agency/react-native-map-link/blob/master/README.md).

> Using the `showLocation` function will shown an action sheet on iOS and an alert on Android

I've followed the post-install step of expo, which is in this [document](https://github.com/flexible-agency/react-native-map-link/blob/master/docs/expo.md). And already rebuild the app.
Is there any extra dependancies I need to install?
My environment:
```
expo: 43.0.0
react-native: 0.64.3
```

**Comment by tschoffelen** [comment]
The library automatically opens the app if there's only one app in the list.

This can be because of a couple of things:

- You only have one supported maps app installed
- You haven't properly executed the post-install steps, or haven't re-built the native part of the app
- Or you're using the Expo app to debug whilst testing, which doesn't have any external apps whitelisted to open. Once you compile the app yourself, it should work

**Comment by kr2goApp** [comment]
I've the same problem with my Samsung Note 10 and Xiomi S9. On Huawei and iOS works fine.
This is my code:
          showLocation({
            latitude: latitudeValue,
            longitude: longitudeValue,
            alwaysIncludeGoogle: true,
            dialogTitle: "Title Value",
            dialogMessage: "Dialog Message",
            cancelText: "Cancel Text",
            appsWhiteList: ['google-maps', 'waze'],
          })

Any idea?

**Comment by qaws5503** [comment]
[UPDATES]: @tschoffelen When I upgrade to Expo SDK44. My Pixel 5 doesn't have any available apps when I use `popup`.(My device has install google-map and uber)
Is there any new changes in android? And sorry I don't have a iOS device to test this problem exist in iOS or not.

**Comment by qaws5503** [comment]
[SOLVED]: #212
